apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: service-b
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      run: service-b
  template:
    metadata:
      labels:
        run: service-b
    spec:
      containers:
      - name: service-b
        image: stephpr/service-b
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: service-b
  name: service-b
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: service-b
